rust: stable
language: rust
cache: cargo # Cache cargo for quicker builds
sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before-script:
  - rustup component add clippy
  - rustup component add rustfmt
  - rustup component add llvm-tools-preview
  - cargo install cargo-binutils # Install binutils for stripping binaries

script:
  - rustc -Vv
  - rustup -V
  - cargo -V
  - cargo test --all-targets --all-features -v
  - cargo clippy --all-targets --all-features -- -D warnings -v
  - cargo fmt --all -- --check -v
  - cargo build --release -v

matrix:
  include:
    # Linux 64bit
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl

    # Linux 32bit
    - os: linux
      env: TARGET=i686-unknown-linux-musl

    # OSX 64bit
    - os: osx
      env: TARGET=x86_64-apple-darwin

    # Windows 64bit
    - os: windows
      env: TARGET=x86_64-pc-windows-msvc

    # Windows 32bit
    - os: windows
      env: TARGET=i686-pc-windows-msvc

install:
  - rustup target add $TARGET

before_deploy:
  - |
    (
    cargo build --release --target $TARGET    
    if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
      cp target/${TARGET}/release/crunch.exe crunch-${TRAVIS_TAG}-${TARGET}.exe
      cargo strip crunch-${TRAVIS_TAG}-${TARGET}.exe -- --strip-all
    else
      cp target/${TARGET}/release/crunch crunch-${TRAVIS_TAG}-${TARGET}
      cargo strip crunch-${TRAVIS_TAG}-${TARGET} -- --strip-all
    fi
    )

deploy:
  api_key:
    secure: "GITHUB OAUTH TOKEN"

  file: crunch-${TRAVIS_TAG}-${TARGET}*
  file_glob: true

  on:
    tags: true

  provider: releases
  skip_cleanup: true

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/examplerust-*; do [ -x "${file}" ] || continue; mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
