[package]
name = "crunch"
version = "0.0.0"
authors = ["Chase Wilson <contact@chasewilson.dev>"]
publish = false
description = "An esoteric language written in Rust"
homepage = "https://github.com/Kixiron/crunch-lang"
repository = "https://github.com/Kixiron/crunch-lang"
readme = "README.md"
keywords = ["crunch", "language"]
categories = ["language"]
license = "MIT OR Apache-2.0"
edition = "2018"

[[bin]]
name = "crunch"
path = "src/bin.rs"

[[bench]]
name = "vm_execution"
harness = false

[dependencies]
log = "0.4.8"
simple_logger = "1.3.0"
color-backtrace = "0.3.0"
array-init = "0.1.1"
logos = "0.10.0-rc2"
structopt = "0.3.5"
codespan = "0.6.0"
codespan-reporting = "0.6.0"
human-panic = "1.0.1"
string-interner = "0.7.1"
rand = { version = "0.7.2", features = ["small_rng"] }
lazy_static = "1.4.0"
libloading = "0.5.2"
num-bigint = "0.2.3"
crunch_proc_macro = { path = "./crates/crunch_proc_macro" }
dynasm = "0.5.2"
dynasmrt = "0.5.2"
# no-panic = "0.1.12"
once_cell = "1.2.0"

[target.'cfg(target_family = "windows")'.dependencies]
winapi = "0.3.8"

[target.'cfg(target_family = "unix")'.dependencies]
libc = "0.2.66"

[dev-dependencies]
criterion = "0.3.0"
proptest = "0.9.4"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
incremental = false
overflow-checks = false

[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
incremental = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/Kixiron/crunch-lang" }
is-it-maintained-open-issues = { repository = "https://github.com/Kixiron/crunch-lang" }
maintenance = { status = "experimental" }
