[workspace]
members = ["crates/*", "crates/crunch-typecheck/typecheck_ddlog"]
exclude = ["crates/crunch-fuzzing", "crates/repl"]

[profile.release]
debug = false
opt-level = 3
debug-assertions = false
lto = "fat"
codegen-units = 1
