[package]
name = "crunch"
version = "0.0.0"
authors = ["Chase Wilson <chase.h.wilson3@gamil.com>"]
publish = false
description = "An esoteric language written in Rust"
homepage = "https://github.com/Kixiron/crunch-lang"
repository = "https://github.com/Kixiron/crunch-lang"
readme = "README.md"
keywords = ["crunch", "language"]
categories = ["language"]
license = "MIT"
edition = "2018"

[[bin]]
name = "crunch"
path = "src/bin.rs"

[[bench]]
name = "vm_execution"
harness = false

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
derive_more = "0.15.0"
shrinkwraprs = "0.2.1"
log = "0.4.8"
simple_logger = "1.3.0"
color-backtrace = "0.2.3"
array-init = "0.1.0"
logos = "0.10.0-rc2"
structopt = "0.3.2"
require_unsafe_in_body = "0.2.0"
pest = "2.1.2"
pest_derive = "2.1.0"
codespan = "0.4.1"
codespan-reporting = "0.4.1"

[target.'cfg(target_family = "windows")'.dependencies]
winapi = "0.3.8"

[target.'cfg(target_family = "unix")'.dependencies]
libc = "0.2.62"

[dev-dependencies]
criterion = "0.3.0"
simple_logger = "1.3.0"
color-backtrace = "0.2.3"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
incremental = false
overflow-checks = false

[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
incremental = true
overflow-checks = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/Kixiron/crunch-lang" }
is-it-maintained-open-issues = { repository = "https://github.com/Kixiron/crunch-lang" }
maintenance = { status = "experimental" }
