[package]
name = "ladder"
version = "0.1.0"
authors = ["Chase Wilson <me@chasewilson.dev>"]
edition = "2018"

[dependencies.crunch-shared]
path = "../crunch-shared"

[dev-dependencies.crunch-parser]
path = "../crunch-parser"
