<<<<<<< HEAD
sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable

script:
  - cargo test
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo build --no-default-features;
    fi
=======
sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable

script:
  - cargo test
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo build --no-default-features;
    fi
>>>>>>> Refractored, fixed and tested int parser
