[package]
name = "crunch-proc"
version = "0.1.0"
authors = ["Chase Wilson <me@chasewilson.dev>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies.syn]
version = "1.0.23"
features = ["full"]

[dependencies.quote]
version = "1.0.6"

[dependencies.proc-macro2]
version = "1.0.15"
