[package]
name = "mark-and-sweep"
version = "0.1.0"
authors = ["Chase Wilson <contact@chasewilson.dev>"]
edition = "2018"

[dependencies]

[target.'cfg(target_family = "windows")'.dependencies]
winapi = "0.3.8"

[target.'cfg(target_family = "unix")'.dependencies]
libc = "0.2.66"
