[package]
name = "crunch-parser"
version = "0.0.0"
description = "A small language"
authors = ["Kixiron <contact.kixiron@gmail.com>"]
edition = "2018"
license = "MIT"
# readme = "README.md"

[dependencies]
crunch-token = { path = "../crunch-token" }
crunch-error = { path = "../crunch-error" }
shrinkwraprs = "0.2.1"
codespan-reporting = "0.3.0"
typed-arena = { path = "../typed-arena" }
lazy_static = "1.3.0"
once_cell = "0.2.1"

[dev-dependencies]
proptest = "0.9.4"
