[package]
name = "crunch-parser"
version = "0.1.0"
authors = ["Chase Wilson <contact@chasewilson.dev>"]
edition = "2018"

[dependencies.string-interner]
version = "0.7.1"

[dependencies.logos]
version = "0.10.0-rc2"

[dependencies.crunch-error]
path = "../crunch-error"

[dependencies.randomize]
version = "3.0.1"
default-features = false

[dependencies.hashbrown]
version = "0.7.1"

[dependencies.pipeline-job]
path = "../pipeline-job"

[dev-dependencies.simple_logger]
version = "1.6.0"
default-features = false
