[package]
name = "crunch-parser"
version = "0.0.0"
description = "A small language"
authors = ["Kixiron <contact.kixiron@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
crunch-token = { path = "../crunch-token" }
crunch-error = { path = "../crunch-error" }
shrinkwraprs = "0.2.1"
codespan-reporting = "0.3.0"
typed-arena = { path = "../typed-arena" }
lazy_static = "1.3.0"
once_cell = "0.2.1"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 16
panic = 'unwind'
incremental = true
overflow-checks = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
panic = 'unwind'
incremental = false
overflow-checks = false

[profile.test]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false
