[package]
name = "crunch-parser"
version = "0.1.0"
authors = ["Chase Wilson <contact@chasewilson.dev>"]
edition = "2018"

[dependencies.string-interner]
version = "0.7.1"

[dependencies.logos]
version = "0.10.0-rc2"

[dependencies.hexponent]
version = "0.2.3"
default-features = false

[dependencies.hashbrown]
version = "0.7.1"

[dependencies.parking_lot]
version = "0.10.0"
default-features = false

[dependencies.crunch-error]
path = "../crunch-error"

[dependencies.pipeline-job]
path = "../pipeline-job"
