[package]
name = "crunch-mir"
version = "0.1.0"
authors = ["Chase Wilson <me@chasewilson.dev>"]
edition = "2018"

[dependencies.crunch-shared]
path = "../crunch-shared"

[dependencies.ladder]
path = "../ladder"

[dependencies.crunch-typecheck]
path = "../crunch-typecheck"
