[package]
name = "crunch-semantics"
version = "0.1.0"
authors = ["Chase Wilson <contact@chasewilson.dev>"]
license = "Zlib"
edition = "2018"

[features]
no-std = ["crunch-shared/no-std"]

[dependencies.crunch-shared]
path = "../crunch-shared"
