[package]
name = "crunch-error"
version = "0.1.0"
authors = ["Chase Wilson <contact@chasewilson.dev>"]
edition = "2018"

[dependencies.codespan]
version = "0.6.0"

[dependencies.codespan-reporting]
version = "0.6.0"

[dependencies.log]
version = "0.4.8"
