name: Rust

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        rustup component add clippy
        rustup component add rustfmt
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Rustfmt
      run: cargo fmt --all -- --check
  
  windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        rustup component add clippy
        rustup component add rustfmt
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Rustfmt
      run: cargo fmt --all -- --check
